spring:
  application:
    name: sb40k

  datasource:
    url: jdbc:mysql://localhost:3306/sb40db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: abcd1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  security:
    enable: false
    enable-csrf: false
    user:
      name: admin
      password: admin123

mybatis-plus:
  global-config:
    db-config:
      column-format: "c_%s"
      id-type: auto
      ddl-auto: update
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081
  forward-headers-strategy: framework


logging:
  level:
    com.github.jingshouyan.sb40k.mapper: debug

socketio:
  port: 8080

biz:
  snowflake-worker-id: 0
  mask-settings:
    username: 22
    password: 11
    email: 33

kind: Application
